### ISSUE TITLE
Error Running npm install worker-render

### ISSUE THREAD

**Issue by RALifeCoach** [canjs/worker-render#15]
```
./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /git/pgatour-cq-v2/front-end/node_modules/canvas
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:canvas@1.1.6 canvas@1.1.6 install: `node-gyp rebuild`
npm WARN install:canvas@1.1.6 Exit status 1
```

**Comment by matthewp** [comment]
You sure this isn't caused by some other dep you have? In a fresh project I get no errors.  Also, worker-render has no native deps.

**Comment by RALifeCoach** [comment]
You are right - it must be another dependency that is causing the problem. It installs fine in an empty folder. I will extract the dist folder from there.

**Comment by matthewp** [comment]
Cool.
